# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:03
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='head_photo',
            field=models.ImageField(null=True, upload_to=accounts.models.user_directory_path),
        ),
    ]
